# Generated by Django 2.2 on 2020-05-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0003_auto_20200514_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datosuser',
            old_name='userDNI',
            new_name='idUser',
        ),
    ]
