# Generated by Django 2.2 on 2020-05-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_auto_20200514_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='fotoUser',
            field=models.ImageField(upload_to='perfiles/img', verbose_name='Foto de perfil'),
        ),
    ]
