# Generated by Django 2.2 on 2020-05-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0005_auto_20200520_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='fotoUser',
            field=models.ImageField(upload_to='img/perfiles', verbose_name='Foto de perfil'),
        ),
    ]
