# Generated by Django 2.2 on 2020-05-21 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userdata', '0005_auto_20200520_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategProye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lenguaje', models.CharField(max_length=255, verbose_name='Lenguaje que utilizó en el proyecto')),
                ('motorDB', models.CharField(max_length=255, verbose_name='Motor de bade de datos utilizado en el proyecto')),
                ('arquitectura', models.CharField(max_length=255, verbose_name='Arquitectura del proyecto')),
            ],
            options={
                'verbose_name': 'Categorias de los proyectos',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombTipoDocu', models.CharField(max_length=255, verbose_name='Nombre del tipo de proyecto')),
            ],
            options={
                'verbose_name': 'Tipo de documentos de los proyectos',
                'verbose_name_plural': 'Tipo de proyecto',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombProye', models.CharField(max_length=200, null=True, verbose_name='Nombre del proyecto')),
                ('descProye', models.CharField(max_length=200, null=True, verbose_name='Descripción del proyecto')),
                ('imgProye', models.ImageField(max_length=200, upload_to='perfiles/img', verbose_name='Imagen del proyecto')),
                ('urlRepo', models.CharField(max_length=100, verbose_name='Link del repositorio')),
                ('fechaInicio', models.DateTimeField(verbose_name='Fue iniciado el')),
                ('fechaFinal', models.DateTimeField(verbose_name='Fue terminado el')),
                ('statusProye', models.DateTimeField(max_length=200, verbose_name='Estado del proyecto')),
                ('idCateProye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CategProye', verbose_name='Identificación de la categoria del proyecto')),
            ],
            options={
                'verbose_name': 'Proyectos de los usuarios',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombDocu', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('pathDocu', models.CharField(max_length=255, verbose_name='Ruta del documento')),
                ('idTipoDocu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu', verbose_name='Identificación del tipo de proyecto')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Identificación del usuario')),
                ('nombProye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Identificación del proyecto')),
            ],
            options={
                'verbose_name': 'Documentos del proyecto',
                'verbose_name_plural': 'Documetos',
            },
        ),
    ]
