# Generated by Django 2.2 on 2020-05-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categproye',
            options={'verbose_name': 'Categorias de los proyectos', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='documentos',
            options={'verbose_name': 'Documentos del proyecto', 'verbose_name_plural': 'Documentos'},
        ),
    ]
